name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Upgrade pip
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run tests
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest 

      # Step 6: Create archive of dependencies
      - name: Create archive of dependencies
        run: |
          cd ./venv/lib/python3.9/site-packages
          zip -r9 ${GITHUB_WORKSPACE}/api.zip .

      # Step 7: Add API files to the zip
      - name: Add API files to Zip file
        run: |
          cd ${GITHUB_WORKSPACE}/api
          zip -g ../api.zip -r *  # Ensure we add files within the api folder

      # Step 8: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ./api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Lambda artifact
        uses: actions/download-artifact@v3
        with:
          name: api
          path: api.zip

      - name: Upload to S3
        run: aws s3 cp api.zip s3://fastapi/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name fastapi --s3-bucket fastapi --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  