name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Upgrade pip
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 5: Run tests
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/

      # Step 6: Create archive of dependencies
      - name: Create archive of dependencies
        run: |
          cd ./venv/lib/python3.8/site-packages
          zip -r9 ${GITHUB_WORKSPACE}/api.zip .

      # Step 7: Add API files to the zip
      - name: Add API files to Zip file
        run: |
          cd ./api && zip -g ../api.zip -r .

      # Step 8: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ./api.zip
